package notifier

import (
	"bytes"
	"context"
	"crypto/tls"
	"fmt"
	"html/template"
	"net/smtp"
	"os"
	"strings"
	"time"

	"github.com/dimaskiddo/lmd-ng/internal/config"
	"github.com/dimaskiddo/lmd-ng/internal/log"
)

// emailHTMLTemplate is the HTML template for quarantine notification emails.
// Parsed once at EmailNotifier construction time.
const emailHTMLTemplate = `
<!DOCTYPE html>
<html>
<head>
<style>
	body { font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; }
	.container { background-color: #fff; margin: 20px auto; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1); max-width: 600px; border-top: 5px solid #d9534f; }
	h2 { color: #d9534f; margin-top: 0; }
	table { width: 100%; border-collapse: collapse; margin-top: 15px; }
	th, td { text-align: left; padding: 10px; border-bottom: 1px solid #ddd; word-break: break-all; }
	th { background-color: #f8f8f8; width: 30%; white-space: nowrap; }
	.footer { margin-top: 20px; font-size: 12px; color: #777; text-align: center; }
</style>
</head>
<body>
<div class="container">
	<h2>LMD-NG Malware Alert</h2>
	<p>Malware has been detected and successfully quarantined on <strong>{{.Hostname}}</strong>.</p>
	<table>
		<tr><th>Host</th><td>{{.Hostname}}</td></tr>
		<tr><th>Time</th><td>{{.Timestamp}}</td></tr>
		<tr><th>File Path</th><td><code>{{.FilePath}}</code></td></tr>
		<tr><th>Signature</th><td>{{.SignatureName}}</td></tr>
	</table>
	<div class="footer">
		This is an automated notification generated by Linux Malware Detect - Next Generation.
	</div>
</div>
</body>
</html>
`

// EmailNotifier handles sending email notifications for malware detections.
type EmailNotifier struct {
	cfg  *config.EmailNotificationConfig
	tmpl *template.Template
}

// NewEmailNotifier creates a new EmailNotifier with the given configuration.
// The HTML template is parsed once at construction time.
func NewEmailNotifier(cfg *config.EmailNotificationConfig) *EmailNotifier {
	tmpl, err := template.New("email").Parse(emailHTMLTemplate)
	if err != nil {
		// Template is a compile-time constant — parse failure is a programming error
		log.Error("Failed to parse email template (programming error)", "error", err)
	}
	return &EmailNotifier{
		cfg:  cfg,
		tmpl: tmpl,
	}
}

// SendQuarantineNotification sends an HTML email notification indicating a file was quarantined.
func (n *EmailNotifier) SendQuarantineNotification(ctx context.Context, filePath, signatureName string) error {
	if !n.cfg.Enabled || len(n.cfg.Recipients) == 0 {
		return nil
	}

	// Early context cancellation check
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	hostname, err := os.Hostname()
	if err != nil {
		log.Debug("Failed to get hostname, using fallback", "error", err)
		hostname = "Unknown"
	}

	// Prepare data for the template
	data := struct {
		Hostname      string
		Timestamp     string
		FilePath      string
		SignatureName string
	}{
		Hostname:      hostname,
		Timestamp:     time.Now().Format(time.RFC1123),
		FilePath:      filePath,
		SignatureName: signatureName,
	}

	var body bytes.Buffer
	if err := n.tmpl.Execute(&body, data); err != nil {
		return fmt.Errorf("failed to execute email template: %w", err)
	}

	// Build the email headers and MIME multipart (or just HTML)
	mime := "MIME-version: 1.0;\nContent-Type: text/html; charset=\"UTF-8\";\n\n"
	subject := fmt.Sprintf("Subject: [LMD-NG Alert] Malware Quarantined on %s\r\n", hostname)
	toHeader := fmt.Sprintf("To: %s\r\n", strings.Join(n.cfg.Recipients, ","))
	fromHeader := fmt.Sprintf("From: %s\r\n", n.cfg.Sender)
	msg := []byte(subject + fromHeader + toHeader + mime + body.String())
	addr := fmt.Sprintf("%s:%d", n.cfg.SMTPHost, n.cfg.SMTPPort)

	var auth smtp.Auth
	if n.cfg.SMTPUsername != "" {
		auth = smtp.PlainAuth("", n.cfg.SMTPUsername, n.cfg.SMTPPassword, n.cfg.SMTPHost)
	}

	// Send email based on SSL/TLS setting
	if n.cfg.SMTPUseSSLTLS {
		tlsconfig := &tls.Config{
			ServerName: n.cfg.SMTPHost,
		}

		dialer := &tls.Dialer{Config: tlsconfig}
		conn, err := dialer.DialContext(ctx, "tcp", addr)
		if err != nil {
			return fmt.Errorf("failed to connect to SMTP server with TLS: %w", err)
		}
		defer conn.Close()

		c, err := smtp.NewClient(conn, n.cfg.SMTPHost)
		if err != nil {
			return fmt.Errorf("failed to create SMTP client: %w", err)
		}

		if auth != nil {
			if ok, _ := c.Extension("AUTH"); ok {
				if err = c.Auth(auth); err != nil {
					return fmt.Errorf("failed to authenticate: %w", err)
				}
			}
		}

		if err = c.Mail(n.cfg.Sender); err != nil {
			return fmt.Errorf("failed to set sender: %w", err)
		}

		for _, recipient := range n.cfg.Recipients {
			if err = c.Rcpt(recipient); err != nil {
				return fmt.Errorf("failed to set recipient: %w", err)
			}
		}

		w, err := c.Data()
		if err != nil {
			return fmt.Errorf("failed to send DATA command: %w", err)
		}

		_, err = w.Write(msg)
		if err != nil {
			return fmt.Errorf("failed to write email body: %w", err)
		}

		err = w.Close()
		if err != nil {
			return fmt.Errorf("failed to close data writer: %w", err)
		}

		c.Quit()
	} else {
		err := smtp.SendMail(addr, auth, n.cfg.Sender, n.cfg.Recipients, msg)
		if err != nil {
			return fmt.Errorf("failed to send email via standard SMTP: %w", err)
		}
	}

	log.Info("Quarantine notification email sent successfully", "recipients", len(n.cfg.Recipients))
	return nil
}

// SendAlert sends a high-priority plain-text alert email (used for integrity /
// tamper failures, where an HTML template is not needed).
func (n *EmailNotifier) SendAlert(ctx context.Context, title, message string) error {
	if !n.cfg.Enabled || len(n.cfg.Recipients) == 0 {
		return nil
	}

	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}

	hostname, err := os.Hostname()
	if err != nil {
		log.Debug("Failed to get hostname, using fallback", "error", err)
		hostname = "Unknown"
	}

	timestamp := time.Now().Format(time.RFC1123)
	subject := fmt.Sprintf("Subject: [LMD-NG ALERT] %s on %s\r\n", title, hostname)
	toHeader := fmt.Sprintf("To: %s\r\n", strings.Join(n.cfg.Recipients, ","))
	fromHeader := fmt.Sprintf("From: %s\r\n", n.cfg.Sender)
	mime := "MIME-version: 1.0;\nContent-Type: text/plain; charset=\"UTF-8\";\n\n"
	body := fmt.Sprintf("LMD-NG Alert\n\nHost: %s\nTime: %s\n\n%s\n\n%s",
		hostname, timestamp, title, message)
	msg := []byte(subject + fromHeader + toHeader + mime + body)
	addr := fmt.Sprintf("%s:%d", n.cfg.SMTPHost, n.cfg.SMTPPort)

	var auth smtp.Auth
	if n.cfg.SMTPUsername != "" {
		auth = smtp.PlainAuth("", n.cfg.SMTPUsername, n.cfg.SMTPPassword, n.cfg.SMTPHost)
	}

	var sendErr error
	if n.cfg.SMTPUseSSLTLS {
		tlsconfig := &tls.Config{ServerName: n.cfg.SMTPHost}
		dialer := &tls.Dialer{Config: tlsconfig}
		conn, cerr := dialer.DialContext(ctx, "tcp", addr)
		if cerr != nil {
			return fmt.Errorf("failed to connect to SMTP server with TLS: %w", cerr)
		}
		defer conn.Close()

		c, cerr := smtp.NewClient(conn, n.cfg.SMTPHost)
		if cerr != nil {
			return fmt.Errorf("failed to create SMTP client: %w", cerr)
		}

		if auth != nil {
			if ok, _ := c.Extension("AUTH"); ok {
				if err := c.Auth(auth); err != nil {
					return fmt.Errorf("failed to authenticate: %w", err)
				}
			}
		}

		if err := c.Mail(n.cfg.Sender); err != nil {
			return fmt.Errorf("failed to set sender: %w", err)
		}
		for _, recipient := range n.cfg.Recipients {
			if err := c.Rcpt(recipient); err != nil {
				return fmt.Errorf("failed to set recipient: %w", err)
			}
		}
		w, werr := c.Data()
		if werr != nil {
			return fmt.Errorf("failed to send DATA command: %w", werr)
		}
		if _, err := w.Write(msg); err != nil {
			return fmt.Errorf("failed to write email body: %w", err)
		}
		if err := w.Close(); err != nil {
			return fmt.Errorf("failed to close data writer: %w", err)
		}
		c.Quit()
	} else {
		sendErr = smtp.SendMail(addr, auth, n.cfg.Sender, n.cfg.Recipients, msg)
		if sendErr != nil {
			return fmt.Errorf("failed to send email via standard SMTP: %w", sendErr)
		}
	}

	log.Info("Alert notification email sent successfully", "title", title, "recipients", len(n.cfg.Recipients))
	return nil
}
