package notifier

import (
	"bytes"
	"crypto/tls"
	"fmt"
	"html/template"
	"net/smtp"
	"os"
	"strings"
	"time"

	"github.com/dimaskiddo/lmd-ng/internal/config"
	"github.com/dimaskiddo/lmd-ng/internal/log"
)

// EmailNotifier handles sending email notifications for malware detections.
type EmailNotifier struct {
	cfg *config.EmailNotificationConfig
}

// NewEmailNotifier creates a new EmailNotifier with the given configuration.
func NewEmailNotifier(cfg *config.EmailNotificationConfig) *EmailNotifier {
	return &EmailNotifier{
		cfg: cfg,
	}
}

// SendQuarantineNotification sends an HTML email notification indicating a file was quarantined.
func (n *EmailNotifier) SendQuarantineNotification(filePath, signatureName string) error {
	if !n.cfg.Enabled || len(n.cfg.Recipients) == 0 {
		return nil
	}

	hostname, _ := os.Hostname()
	if hostname == "" {
		hostname = "Unknown"
	}

	// Prepare data for the template
	data := struct {
		Hostname      string
		Timestamp     string
		FilePath      string
		SignatureName string
	}{
		Hostname:      hostname,
		Timestamp:     time.Now().Format(time.RFC1123),
		FilePath:      filePath,
		SignatureName: signatureName,
	}

	// HTML template design
	const htmlTemplate = `
<!DOCTYPE html>
<html>
<head>
<style>
	body { font-family: Arial, sans-serif; background-color: #f4f4f4; color: #333; }
	.container { background-color: #fff; margin: 20px auto; padding: 20px; border-radius: 5px; box-shadow: 0 0 10px rgba(0,0,0,0.1); max-width: 600px; border-top: 5px solid #d9534f; }
	h2 { color: #d9534f; margin-top: 0; }
	table { width: 100%; border-collapse: collapse; margin-top: 15px; }
	th, td { text-align: left; padding: 10px; border-bottom: 1px solid #ddd; word-break: break-all; }
	th { background-color: #f8f8f8; width: 30%; white-space: nowrap; }
	.footer { margin-top: 20px; font-size: 12px; color: #777; text-align: center; }
</style>
</head>
<body>
<div class="container">
	<h2>LMD-NG Malware Alert</h2>
	<p>Malware has been detected and successfully quarantined on <strong>{{.Hostname}}</strong>.</p>
	<table>
		<tr><th>Host</th><td>{{.Hostname}}</td></tr>
		<tr><th>Time</th><td>{{.Timestamp}}</td></tr>
		<tr><th>File Path</th><td><code>{{.FilePath}}</code></td></tr>
		<tr><th>Signature</th><td>{{.SignatureName}}</td></tr>
	</table>
	<div class="footer">
		This is an automated notification generated by Linux Malware Detect - Next Generation.
	</div>
</div>
</body>
</html>
`

	tmpl, err := template.New("email").Parse(htmlTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse email template: %w", err)
	}

	var body bytes.Buffer
	if err := tmpl.Execute(&body, data); err != nil {
		return fmt.Errorf("failed to execute email template: %w", err)
	}

	// Build the email headers and MIME multipart (or just HTML)
	mime := "MIME-version: 1.0;\nContent-Type: text/html; charset=\"UTF-8\";\n\n"
	subject := fmt.Sprintf("Subject: [LMD-NG Alert] Malware Quarantined on %s\r\n", hostname)
	toHeader := fmt.Sprintf("To: %s\r\n", strings.Join(n.cfg.Recipients, ","))
	fromHeader := fmt.Sprintf("From: %s\r\n", n.cfg.Sender)
	msg := []byte(subject + fromHeader + toHeader + mime + body.String())
	addr := fmt.Sprintf("%s:%d", n.cfg.SMTPHost, n.cfg.SMTPPort)

	var auth smtp.Auth
	if n.cfg.SMTPUsername != "" {
		auth = smtp.PlainAuth("", n.cfg.SMTPUsername, n.cfg.SMTPPassword, n.cfg.SMTPHost)
	}

	// Send email based on SSL/TLS setting
	if n.cfg.SMTPUseSSLTLS {
		tlsconfig := &tls.Config{
			ServerName: n.cfg.SMTPHost,
		}

		conn, err := tls.Dial("tcp", addr, tlsconfig)
		if err != nil {
			return fmt.Errorf("failed to connect to SMTP server with TLS: %w", err)
		}
		defer conn.Close()

		c, err := smtp.NewClient(conn, n.cfg.SMTPHost)
		if err != nil {
			return fmt.Errorf("failed to create SMTP client: %w", err)
		}

		if auth != nil {
			if ok, _ := c.Extension("AUTH"); ok {
				if err = c.Auth(auth); err != nil {
					return fmt.Errorf("failed to authenticate: %w", err)
				}
			}
		}

		if err = c.Mail(n.cfg.Sender); err != nil {
			return fmt.Errorf("failed to set sender: %w", err)
		}

		for _, recipient := range n.cfg.Recipients {
			if err = c.Rcpt(recipient); err != nil {
				return fmt.Errorf("failed to set recipient: %w", err)
			}
		}

		w, err := c.Data()
		if err != nil {
			return fmt.Errorf("failed to send DATA command: %w", err)
		}

		_, err = w.Write(msg)
		if err != nil {
			return fmt.Errorf("failed to write email body: %w", err)
		}

		err = w.Close()
		if err != nil {
			return fmt.Errorf("failed to close data writer: %w", err)
		}

		c.Quit()
	} else {
		err = smtp.SendMail(addr, auth, n.cfg.Sender, n.cfg.Recipients, msg)
		if err != nil {
			return fmt.Errorf("failed to send email via standard SMTP: %w", err)
		}
	}

	log.Info("Quarantine notification email sent successfully", "recipients", len(n.cfg.Recipients))
	return nil
}
